### ISSUE TITLE
Session Problem - Contao 3.5.9

### ISSUE THREAD

**Issue by gmodesignz** [derhaeuptling/Contao-multi-file-upload-with-DropZone#1]
We used this plugin on a project. Our client found out today that while a user fills in the form, and uploads a file, any other user visiting the site (from anywhere else), will see the uploaded file in their own form.
Even worse, if the second user sends the form first, the upload if user 1 will be attached to the mail of user 2.

**Comment by Metis77** [comment]
Thank you for that.

While investigating I fail to reproduce that.
I even tried with deactivated token and IP check.

Can you help by describing how exactly to reproduce this issue?

**Comment by Metis77** [comment]
Ok I can reproduce that, but only with Page HTML Cache enabled.

You should not enable the html cache for pages that have a form, as the form needs to be generated dynamically (what files are already loaded).

Does this solve you issue?

**Comment by gmodesignz** [comment]
Yes that solves the problem. Thanks!
Great job on that plugin BTW...

**Comment by Metis77** [comment]
Thanks, I appreciate this.
