### ISSUE TITLE
Schnittstelle an EFG

### ISSUE THREAD

**Issue by LinusHe** [derhaeuptling/Contao-multi-file-upload-with-DropZone#11]
Hallo,

ich versende die Bestätigunsmails mit dem Contao Plugin EFG (https://contao.org/de/erweiterungsliste/view/efg.20020019.de.html).
Ich kann hier jedoch nicht die Daten, die ich mit Ihrem Plugin hochlade an die Mails anhängen / verlinken.

Wäre es möglich hier eine Schnittstelle zu programmieren mit geringem Aufwand?

Wenn nicht, hätte ich noch eine kleine andere Frage:
Ich könnte auch, auf EFG verzichten, wenn die Mails von Contao besser formatiert werden würden.
Kann man an der Mail formatierung in Contao etwas umstellen? Also, dass nach jedem Feld eine Leerzeile kommt, bevor das nächste Feld aufgelistet wird?

Ich nutze die neueste Version Ihres Plugins mit Contao 3.5.27.

Vielen Dank für Ihre Hilfe

**Comment by Metis77** [comment]
Hallo Linus probiere mal das Plugin Notification Center

Sent from Nine<http://www.9folders.com/>
________________________________
Von: LinusHe <notifications@github.com>
Gesendet: 20.07.2017 12:38 nachm.
An: derhaeuptling/contao-multi-file-upload-with-dropzone
Cc: Subscribed
Betreff: [derhaeuptling/contao-multi-file-upload-with-dropzone] Schnittstelle an EFG (#11)


Hallo,

ich versende die Bestätigunsmails mit dem Contao Plugin EFG (https://contao.org/de/erweiterungsliste/view/efg.20020019.de.html).
Ich kann hier jedoch nicht die Daten, die ich mit Ihrem Plugin hochlade an die Mails anhängen / verlinken.

Wäre es möglich hier eine Schnittstelle zu programmieren mit geringem Aufwand?

Wenn nicht, hätte ich noch eine kleine andere Frage:
Ich könnte auch, auf EFG verzichten, wenn die Mails von Contao besser formatiert werden würden.
Kann man an der Mail formatierung in Contao etwas umstellen? Also, dass nach jedem Feld eine Leerzeile kommt, bevor das nächste Feld aufgelistet wird?

Ich nutze die neueste Version Ihres Plugins mit Contao 3.5.27.

Vielen Dank für Ihre Hilfe

**Comment by LinusHe** [comment]
Danke, aber bei dem Plugin, kann ich auch nicht einstellen, wie ich es möchte. Ich kann dort nur Alle Felder des Formulars in die Email einfügen. Dann werden Sie aber auch wieder so formatiert, wie vorher.

Gibt es noch eine andere Möglichkeit?

**Comment by Metis77** [comment]
Mit Notification Center kannst du deine Mails nach belieben formatieren.

Schau dir ansonsten auch mal das YouTube Video zum Notification Center an:
https://www.youtube.com/watch?v=FUeJkMkDsFc

Allerdings bin ich nicht sicher, ob es auch mit MultifileUpload funktioniert – müsste aber gehen, wenn ich mich recht erinnere.

**Comment by LinusHe** [comment]
Okay Danke für das Video, ich habe es jetzt schon mal geschafft die Benachrichtigungen zu konfigurieren.

Aber bei mir funktioniert es nicht mit MultifileUpload.. Also entweder mache ich etwas falsch oder es geht leider tatsächlich nicht.

**EDIT: Habe es jetzt doch geschafft. Ich hatte das MultifileUpload Feld beim Notification Center Plugin unter "Dateianhänge via Tokens" geschrieben, was nicht geklappt hat. Im Textfeld geht es** :)

Danke für die Hilfe!

**Comment by Metis77** [comment]
Ok, wir schauen uns das mal an.
Aber auf die Schnelle kommen wir leider nicht dazu.

**Comment by havutcuoglu** [comment]
Hi Metis77, 
kann man die multifileupload Erweiterung eigentlich mit EFG Erweiterung verwenden oder ist es nicht möglich?
Da ich auf der Seite ca. 24 mächtige Formulare habe und ich nicht alles umbauen möchte, wollte ich erst fragen, ob diese möglich ist.

**Comment by Metis77** [comment]
Einsatz mit EFG Erweiterung ist nicht vorgesehen.

**Comment by dimejo** [comment]
@LinusHe 
> EDIT: Habe es jetzt doch geschafft. Ich hatte das MultifileUpload Feld beim Notification Center Plugin unter "Dateianhänge via Tokens" geschrieben, was nicht geklappt hat. Im Textfeld geht es :)

Hast Du es geschafft die Dateien an die E-Mail anzuhängen oder sie nur verlinkt?

**Comment by sfx12** [comment]
Hallo, bei mir funktioniert auch nicht mit dem Dateianhänge als tokens"! Als link geht es, jedoch nicht "klickbar" und mehrere links werden nebeneinander anstatt untereinander angezeigt + wie/wo kann ich aus dem http ein https machen ?

**Comment by Metis77** [comment]
Die Entwicklung an diesem Modul ist eingestellt.
Schau dir mal https://github.com/terminal42/contao-fineuploader an.

**Comment by sfx12** [comment]
Hallo nochmals, Danke - jedoch fehlt beim fineuploader die Option im FE zu löschen!!!

Des weiteren ist mir aufgefallen, wenn ich als Trennzeichen für arrays ein {{br}} anstatt z.B. komma setze, (im nfc) werden die Bilder nicht mehr angehängt!

Ein 3. Bug ist auch noch: wenn ich z.B. 3 Bilder hochlade und eines davon die Maximalgröße übersteigt, ich auf abbrechen bei diesem bild klicke (oder testweise auch nicht) werden garkeine Bilder mehr als Anhang gesendet!
