### ISSUE TITLE
Doesn't save to database

### ISSUE THREAD

**Issue by ameotoko** [derhaeuptling/Contao-multi-file-upload-with-DropZone#12]
Hello,
The description for the "File forewarding" in the backend of the field is misleading. It says "How should the uploaded files be attached to the mail, when sending the formdata by mail is activated.", but, in fact, **this settings also affects the database logic**. 

- If it is set to "Attach files", file paths do not get saved into database at all. 
- If it is set to "Link files", then paths are saved to the database, even if I don't use "Send form data by E-mail" setting.

I lost few hours trying to get the extension working, before I accidentally found this out.

**Comment by Metis77** [comment]
thank you!
Can you offer a fix for this?

**Comment by Thoni** [comment]
Hello ameotoko,

please give me the Contao- and extension-version.

**Comment by janoschbatschi** [comment]
Same issue here, although the file doesn't get saved at all. Independent from "How should the uploaded files be attached to the mail, when sending the formdata by mail is activated"

Contao: 3.5.31
Extension: 2.1.0

Other Extensions in use that might conflict: EFG
