### ISSUE TITLE
Dateiupload erfordert Audioberechtigung

### ISSUE THREAD

**Issue by seibtph** [derhaeuptling/Contao-multi-file-upload-with-DropZone#13]
Ich habe auf mobilen Geräten ein Problem beim Upload. Wenn ich auf das Feld klicke um etwas hochzuladen, möchte mein Chrome zulassen, dass er Audio aufnehmen darf. Das macht aber keinen Sinn, da man lediglich jpg und png hochladen darf.

Wie könnte man das denn unterbinden und ist das schonmal bekannt gewesen?

Getestet habe ich es unter Android 7.0 / Chrome. Die Version der Erweiterung ist 2.1.0.

![screenshot_20171006-095719](https://user-images.githubusercontent.com/17127525/31268725-ecf2e0ce-aa7d-11e7-843e-fb6189fefdae.png)

**Comment by Metis77** [comment]
Bei einem kurzen Test, fragt Chrome unter Android 7 mich nur nach Bilder/Video Rechten.

Das ganze liegt wenn dann aber eher am verwendeten Dropzone.js Plugin.
