### ISSUE TITLE
php 7.2 Anpassungen

### ISSUE THREAD

**Issue by Pellinger** [derhaeuptling/Contao-multi-file-upload-with-DropZone#14]
Ich bekomme unter 7.2 einige Fehler ausgeworfen:
`Warning: Use of undefined constant myid - assumed 'myid' (this will throw an Error in a future version of PHP) in system/modules/multifileupload/classes/fileMoveAndAppend.php on line 35`

`Warning: Use of undefined constant myid - assumed 'myid' (this will throw an Error in a future version of PHP) in system/modules/multifileupload/classes/fileMoveAndAppend.php on line 36`

Würde mich freuen, wenn die Erweiterung langfristig erhalten bliebe. Danke!

**Comment by Metis77** [comment]
Die weiterentwicklung dieses Plugins ist leider eingestellt.
Schau dir als alternative mal dieses an: https://github.com/terminal42/contao-fineuploader
