### ISSUE TITLE
form: case "save data to table" and tmp-folders not deleted 

### ISSUE THREAD

**Issue by b-fender** [derhaeuptling/Contao-multi-file-upload-with-DropZone#4]
Hi! 
I have used Your module in a project-form where i had to save the forms data into a database-table. 

Unfortunately the image path was not saved correctly in the database. Because there is no option in the settings of the multifile-module for the case "save formdata to table".
It would be nice, if this option could be added.

For my needs i altered the file classes/fileMoveAndAppend.php because i needed the file-path of the uploaded file without http:// ... :

--- line 109 - commented out the path creation
`
//$arrSubmittedArray[$myElemData->name] .= "\nhttp://" . //$_SERVER['SERVER_NAME'] . '/' . $subfolder . //$uploadFolder.'/'.$storeFolderPreFile . $curFile;
`
--- needed file path without http:
`
$arrSubmittedArray[$myElemData->name] .= $uploadFolder.'/'.$storeFolderPreFile . $curFile;
`

also i noticed, that always, when a form with a multifile-upload-field is loaded in the frontend, a new folder in the multifile-upload tmp folder will be created. But those created folders will never be deleted, only the files in those folders will be deleted after they are uploaded and copied into the right directory. The created folders remain in the tmp folder.

I hope You can follow me... ;-) best regards, Joc

**Comment by Metis77** [comment]
Thank you!
Looks like you could support this project. Do you want to implement those fixes, test them and send a pull request?

**Comment by b-fender** [comment]
I'd like to, but i don't know much about working with github.

**Comment by Metis77** [comment]
Perfect, I appreciate any help!

If you can fix those issues above, I would be happy I you send me a zip file. I can push those then to GitHub.

As you already forked this repository, you could also push your changes to your fork. Than you can make a pull request, that askes me, if I would like to take over your changes (merge them).
Details on how to pull request you find here: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by b-fender** [comment]
The issue "tmp-folders not deleted" was not true. The tmp folders will be deleted when they are older than 3 hours and the upload.php file is loaded.

**Comment by Metis77** [comment]
Thank you for all the testing.
