### ISSUE TITLE
Upload in E-Mail verlinken erzeugt falschen Link

### ISSUE THREAD

**Issue by Floxn** [derhaeuptling/Contao-multi-file-upload-with-DropZone#7]
Hallo,

ich habe festgestellt, dass der erzeugt Link falsch ausgegeben wird, wenn in der E-Mail die Datei direkt verlinkt werden soll.
Ergebnis ist: http://www.domain.de/files/zum/ordner/dateiname.pdffiles/zum/ordner/dateiname.pdf
Hier wird quasi der Dateipfad doppelt hinzugefügt.

Verwendet man aber die Option "Dateien anhängen und verlinken" wird die Verlinkung der Datei korrekt in der E-Mail ausgegeben.

Könnte evtl. hier ein Fehler drin sein?
https://github.com/derhaeuptling/contao-multi-file-upload-with-dropzone/blob/master/classes/fileMoveAndAppend.php#L103-L112

P.s.: vielen Dank für die Erweiterung!

**Comment by Metis77** [comment]
Dies scheint mit 168362f   zusammen zu hängen.
@b-fender magst du dir das mal ansehen?

**Comment by b-fender** [comment]
Soweit ich es sehen kann, liegts an dem Abschnitt über meiner Ergänzung. Dort wird wohl der Pfad nicht richtig ausgegeben.

**Comment by Metis77** [comment]
Ja daran wird es liegen. Der Upload initialisierte jedesmal eine Synchronisierung des Dateisystems.

Jedoch sollte dies seit acfaf46 nicht mehr der Fall sein.
Die neu hochgeladenen files werden direkt in die DB geschrieben.

Welche version des Plugins hast du denn im Einsatz?

**Comment by Floxn** [comment]
Super, danke für fixen. Tut einwandfrei. Ggf. müssten die Uploadfelder im Formular nochmal gespeichert werden.
