### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by basistom** [derhaeuptling/Contao-multi-file-upload-with-DropZone#8]
Hi,

ich hab den Uploader im Einsatz, allerdings habe ich extreme Performance-Probleme. Beim gleichzeitigen Upload von 3 Dateien ca. 100 KB dauert der Upload teilweise über 1 Minuten. Sowohl lokal als auch auf dem Server. Dabei sehe ich in der Timeline nur, dass die upload.php auf pending steht. Gibt es hier schon Erfahrungen?

**Comment by Metis77** [comment]
Derartige Probleme sind mir neu.
Lässt sich das Problem hier (http://contao.derhaeuptling.com/applications.html) reproduzieren?

**Comment by basistom** [comment]
Auf der Seite kann ich das nicht bestätigen. Wie sind die Einstellungen im Uploader?

**Comment by Metis77** [comment]
wie sind sie denn bei dir?
Dann stelle ich das auch auch mal so ein.

**Comment by Metis77** [comment]
Du kannst mir ja einen Screenshot mit den Einstellungen hochladen ;)

**Comment by basistom** [comment]
![screenshot 2017-02-28 14 04 28](https://cloud.githubusercontent.com/assets/4112968/23406354/da6e3960-fdbe-11e6-9894-8dbc31a0dd91.png)

(Natürlich mit einem Ziel, das hab ich nur rausgenommen)

**Comment by basistom** [comment]
Die ganze Seite steht während eines Uploads. Im Ordner sind mittlerweile fast 1,8 GB. Kann das eine Ursache sein?

**Comment by Metis77** [comment]
Ja daran wird es liegen. Der Upload initialisierte jedesmal eine Synchronisierung des Dateisystems.

Jedoch sollte dies seit acfaf46 nicht mehr der Fall sein.
Die neu hochgeladenen files werden direkt in die DB geschrieben.

Welche version des Plugins hast du denn im Einsatz?

**Comment by basistom** [comment]
Ich hab jetzt geupdated und den Folder gelöscht. Damit läuft es. Danke!
