### ISSUE TITLE
Empty temp-folders are not deleted

### ISSUE THREAD

**Issue by ghost** [derhaeuptling/Contao-multi-file-upload-with-DropZone#9]
The extension deletes files after 3 hours when the form was not submitted. However, the numbered folders inside the tmp-folder are not deleted. So as time goes by you get a lot of empty folders like "110", "111", "112", ect. It would be nice if the empty folders inside "tmp" are also deleted.

**Comment by ghost** [comment]
Uuups, my bad. The folders are in fact deleted. Sorry.

**Comment by Metis77** [comment]
no problem.
Thanks anyway for testing ;)
